### ISSUE TITLE
Camera UP

### ISSUE THREAD

**Issue by trincasidra** [Imdeeo/ProjecteMaster#3]
Corregir la exportación de la cámara para que el Up sea correcto.

**Comment by trincasidra** [comment]
Para el UP y dirección de las cámaras, así como para las luces,  multiplicar un vector unitario negativo por la rotación, después hacer el RH etc
 $.pos+((point3 0 0 -1) \* $.transform.rotation)

**Comment by jvikman** [comment]
Lo del RH al final del todo, para cada propiedad.
Lo del inverse sólo multiplicarlo por la posición en los vertices una vez.
Mirar de pasar rotaciones a quats.

**Comment by trincasidra** [comment]
Sólo queda pasar rotaciones a quats.
